### ISSUE TITLE
Cannot find game if moved to different drive

### ISSUE THREAD

**Issue by DysnomianC** [gregstein/AoE2Tools#14]
The hd convert  tool automatically tries to find the steam assets. The tool says that it has located the files (Ready tick).
![image](https://user-images.githubusercontent.com/20263707/51434101-37f9ea00-1cbe-11e9-8c50-b919c663b0f4.png)

However when doing the convert I see that it is looking in the wrong place for the files.
![image](https://user-images.githubusercontent.com/20263707/51434106-5b249980-1cbe-11e9-905b-8ebd8175f14f.png)

The Fix it! button is disabled so I cannot manually select the path for the correct location, which in my case was on D:.
![age2hd](https://user-images.githubusercontent.com/20263707/51434152-4b598500-1cbf-11e9-8094-c0e1ff5c28bc.PNG)

The reason why this is occurring is that if you use steam to move games from one drive to another it will move all the files but leave the folder structure intact (so all the folders are empty). As such the tool is finding the empty Age2HD folder without checking to see if there is an "AoK HD.exe" file.
![image](https://user-images.githubusercontent.com/20263707/51434180-878ce580-1cbf-11e9-9a03-d797ed8bf74e.png)

To solve the issue simply make the tool look for the actual "AoK HD.exe" file not just the Age2HD folder.

I have worked around this issue by temporarily deleting the Age2HD folder on C: but I only knew to do this because of the error message which is not user friendly.

Alternatively let users use the Fix It! button even if the tool finds a directory.

**Comment by gregstein** [comment]
Thank you for this detailed explaination! As I promise you to enable that button for a custom location.
**Option 1: Rename or delete old path of Age2DH**

(a)- Once you rename "C:\Program Files (x86)\Steam\steamapps\common\Age2HD" to something like "C:\Program Files (x86)\Steam\steamapps\common\Age2HD.old" =>Only now Run AoE2Tools > HDToAoC > Then the Fix it button will appear again.

(b)- Or Instead of (a) and In case you don't need that folder anymore, deleting it then Run AoE2Tools > HDToAoC > Then the Fix it button will appear again.

**Option 2: Reset AoE2Tools**

Anyways there's another way to fix it by simply Reseting AoE2Tools like this: 
![resetaoe2tools](https://user-images.githubusercontent.com/16618729/51434598-1882a300-1c65-11e9-81eb-5942715b7357.jpg)

Once you do it. Close the window and start again and this time you will be able to convert without any errors. Fix it button will appear if you have your game installed in a custom location.

**Comment by DysnomianC** [comment]
Thanks for the prompt reply, Option 1 worked for me :)

**Comment by gregstein** [comment]
Any time brother!
