### ISSUE TITLE
testing 3.3 it in win7 x64 bits IT Works, thanks ... But cant have voobly mods offline.

### ISSUE THREAD

**Issue by y4mi** [gregstein/AoE2Tools#20]
im having some visual mods that would like to install offline.
it makes all the process but when open the game i dont see any mod.

**Comment by y4mi** [comment]
i just can use the version 3.1.0.7

**Comment by gregstein** [comment]
Hello y4mi,

Thank you for reporting this! Do you see any particular error window? That might help me to fix the issue faster. 

> I just can use the version 3.1.0.7

If you have scanned with 3.1.0.7, you can uninstall "AoE2Tools" from control panel then install the latest as it will not ask you to scan again. (Uninstalling AoE2Tools does NOT affect your game installation or settings)

If the solution above does not help let me know so I can recompile a new "Launcher.exe" file that do not prompt anything when it detects your game. 

Warm regards,
GregStein

**Comment by y4mi** [comment]
i dont get any message of error it just get freezed with the game detected post that have to clic OK to close it , but i used clean installations, Thanks for Read/Reply.

**Comment by y4mi** [comment]
ive a little question, how does voobly uses the desktop resolutions in the different way when you made a custom resolution with windows.
i made 1600x1024 but all aoe 2 Closes _crashes_ but just can run it with voobly. It Would be nice to get it offline.

**Comment by gregstein** [comment]
So you didn't install the game with AoE2Tools? I recommend so because the crashing should not happen with an AoE2Tools installation.
Here are two methods of installation:

**(1) New Method To Setup Voobly + Age of Empires 2 + WK all at once**

Download and install AoE2Tools https://github.com/gregstein/AoE2Tools/releases Then follow this 3 min video https://www.youtube.com/watch?v=x2YembRq4U0 . <== This should setup and install the game + wk and setup voobly. Also auto logins you to Voobly if you want to.

**(2) Standard Method to Setup Voobly + Age of Empires 2 + WK with AoE2TOols**
Everything in this video: https://www.youtube.com/watch?v=Srhi14fjTkM

> how to run the game in 32 bits offline mode

If you install the game with aoe2tools it comes with window mode and 32bit as well. Right click AoE2Tools Shield > Version > WK or 1.5

![aoe2tools_menu](https://user-images.githubusercontent.com/16618729/56462871-c4ee3580-63ca-11e9-94e7-943aae5e3a15.jpg)

Keep me updated.

**Comment by y4mi** [comment]
well i use AoC Rip, is it necessary to own the game in steam?

**Comment by gregstein** [comment]
Yes! At first it starts in windowed mode but once you launch the game it becomes full screen but if it's not Press F8 > Options > Select your resolution. Done.

**Comment by y4mi** [comment]
testing 3.3 it in win7 x64 bits
ill tell if it ran

**Comment by y4mi** [comment]
Alternative Minimap, Colored Projectiles, Conquerors Shadow Fix V, Enhanced Ice And Snow, Huge Number - AoC, Light Grid Terrain - No Grid Water, Middle Wood, Precision Cursor.

**Comment by gregstein** [comment]
I will take a look at that soon meantime could you try to install this mod: https://www.voobly.com/gamemods/mod/743/Ultra-light-Delightful-grid-NoSnow  Let me know if it works.

**Comment by y4mi** [comment]
yeah sure sorry for the long time , ill test ..

**Comment by y4mi** [comment]
it worked with 3.1.0.7 delightful light gird. Sorry for many posting.

**Comment by gregstein** [comment]
Thanks for reporting this! I will try to fix in the upcoming update of AoE2Tools. I will close it for but feel free to open a new one upon the release of a new version.
Have a good day,
