### ISSUE TITLE
How to remove mods Aoe2Tools gave me during installation

### ISSUE THREAD

**Issue by henkieaardpeer** [gregstein/AoE2Tools#23]
Hi there,

I can't find an option to remove the mods that I was suggested to install during the installation process. In my case I opted for small trees and grid (and maybe idle villager sign as well, but can't check) but I don't like this version of the grid and I would like to install mods in Voobly itself.

There's no info at all in any of these folders (screenshot below) or in Voobly either

![afbeelding](https://user-images.githubusercontent.com/40700989/64863123-6d2fbf80-d634-11e9-9121-f1f1f38690d5.png)

 --
**Anyway, thanks for the great tool and smooth installation,** I do have the following problem with Voobly though: I don't see how a difference is made between choosing AoC or the Expansions in individual games. Sure, I should probably ask this at Voobly (not finding any useful google results...), but you made this tool to make Voobly much less of a hassle to install, so you must be familiar with how much of a pain in the back Voobly can be, especially for noob users like me.

**Comment by gregstein** [comment]
Hello! I'm writing an answer now. Give me a few minutes.

**Comment by gregstein** [comment]
Thank you dear henkieaardpeer! 

### How to remove Grids, Advanced Idle Pointer, Small Trees?
[Uninstall SmallTrees.zip](https://github.com/gregstein/AoE2Tools/files/3610607/Uninstall.SmallTrees.zip)
[Uninstall AIP.zip](https://github.com/gregstein/AoE2Tools/files/3610608/Uninstall.AIP.zip)
[Uninstall Grids.zip](https://github.com/gregstein/AoE2Tools/files/3610609/Uninstall.Grids.zip)

Download these zip files then import them one by one into Voobly Mods manager and install them as in this example follow:

Easy Peasy Lemon Squeezy!

Step 1: Run AoE2Tools > Game Settings Tab > "Voobly Mods" http://prntscr.com/m18cdb

Step 2: Import "Uninstall AIP-BB.Zip" Through "Voobly Mods" http://prntscr.com/m18e1s

Step 3: Check item "Uninstall AIP-BB" and Press Offline Install http://prntscr.com/m18en2

Step 4: (Only onetime It creates a backup for mods then installs your mod) Done. Should See success message http://prntscr.com/m18hey 

Do the same thing for the rest of zip files and dont forget to remove those imports at the end http://prntscr.com/p5qewc

**When you converted with AoE2Tools (http://prntscr.com/p5q2ow) you must have left the fields checked http://prntscr.com/p5q1ql that's why you got the grid and small trees. (So next time you convert make sure none of those fields are checked.)**

### How to differentiate between AOC and Expansion?
http://prntscr.com/p5q8pq

**Comment by kansha-gratitude** [comment]
Thanks for taking the time for writing a extensive guide with useful pictures. This one seems to have worked and I will now try to install new mods through your tool. If I run into further trouble I will reply
I donated some money to you as thanks.

**Comment by gregstein** [comment]
Thank you so much for the donation ❤❤❤❤ Very much appreciated!

Feel free to contact me again. And by the way I am not sure if you have noticed AoE2Tools Cloud. If you are interested in downloading the game in 5 different builds (Iron, Gold, Platinum, etc.) Iron build is shipped without any mods.

I have written a reddit post about it explaining how it works: https://www.reddit.com/r/aoe2/comments/b7g7au/shh_haa_meet_aoe2tools_cloud_1_click_voobly_setup/

Or simply watch this short video https://www.youtube.com/watch?v=x2YembRq4U0

Again thank you for the awesome support and don't forget to join our discord channel https://discordapp.com/invite/jdCgCyx so I grant you the supporter badge and at the same get realtime help anytime.
