### ISSUE TITLE
App forcing WK update to view current recs

### ISSUE THREAD

**Issue by Firearrow5235** [gregstein/AoE2Tools#3]
Perhaps a drop-down menu to select the preferred version of WK should be implemented. Currently AoE2Tools is attempting to force me into downloading WK 5.8, which is not currently rated and the 5.8 version of HD is not yet out of beta. It also won't work for the recs I'm trying to view.

**Comment by gregstein** [comment]
Hello,
Thank you for reporting! 

I was aware of that in fact, I have already started working on ignoring any new unrated version of WK and delivering only latest and currently rated version on voobly.

And concerning dropdown menu to select preferred version of WK, It is definitely possible to implement and It will be on the next release.

What recs are you trying to view? and does the game crash when you try to view them? And please check Task manager to make sure that age of empires 2 is running as "AoE2Tools.exe" process instead of WK.exe or age2_x1.exe?

**Comment by Firearrow5235** [comment]
I wanted to view recs from WK 5.7.2 but when I drop them into AoE2Tools it tells me that WK is out of date and won't run the rec.

**Comment by gregstein** [comment]
Even if it says out of date, you should be able to play the rec. You should install Wololokingdoms again and make sure to check "Both" for a Voobly and Offline installation. Once it's done, a new folder "Games" including  wk offline installation. Now you can view the recs.

**Comment by Firearrow5235** [comment]
I'll give that a try.

**Comment by gregstein** [comment]
let me know how it goes

**Comment by Firearrow5235** [comment]
Worked like a charm. I also read the error message wrong. It stated that "WK was not installed" not "WK is out-of-date".

**Comment by gregstein** [comment]
Thanks for pointing that out! The message should really be "WK is out of date" instead of "WK is not installed". I will fix that too.

**Comment by Firearrow5235** [comment]
No problem!
