### ISSUE TITLE
[Feature Request] Porting kit compatibility

### ISSUE THREAD

**Issue by bastianwegge** [gregstein/AoE2Tools#5]
Hey guys,

I was just searching the web for a solution to run AoE 2 HD on Mac and just discovered, that the mac setup is pretty easy and straight forward. I'm seeing windows file systems and a registry that you can edit, you could say windows emulated. I tried installing AoE2Tools and got no reaction.

Do you think this could be possible? I'd be willing to help and put effort in this, as opening the Wololo Kingdoms to Mac-Owners might really make the community a little bit bigger.

What's your opinion on this?

All the best! 🧙🏼‍♂️

**Comment by gregstein** [comment]
Hello Bastian,
It is actually on my todolist to port AoE2Tools through Mono (crossplatform). I just need to finish some other stuff like improving stability, multilingual support and few more features before I start porting it. That way we have a complete software available for every platform possible.

What makes AoE2Tools not responding or compatible on wine right now is mainly because of advanced P/Invoke calls that need to be replaced and therefore additional debugging. And yes! I will have to open a new github project with an open source code and any help is welcomed with open arms.

After the next release that should include multilingual support, I will start porting.

Thank you,
